### ISSUE TITLE
emapper crashes

### ISSUE THREAD

**Issue by willnotburn** [eggnogdb/eggnog-mapper#105]
**Installation**
As per the website.
`git clone https://github.com/jhcepas/eggnog-mapper.git`

and then
`download_eggnog_data.py euk bact arch viruses`

**Command line**
./emapper.py -i /mnt/ffs17/users/wilburn4/5000/contigs.all.500.grep.chunk_100000.fa -o ./contigs.all.500.grep.chunk_100000.fa -d bact --cpu 20 --usemem

**Error log**
Traceback (most recent call last):
  File "./emapper.py", line 1009, in <module>
    main(args)
  File "./emapper.py", line 226, in main
    dump_hmm_matches(args.input, hmm_hits_file, dbpath, port, scantype, idmap, args)
  File "./emapper.py", line 405, in dump_hmm_matches
    base_tempdir=args.temp_dir)):
  File "/mnt/ls15/scratch/users/wilburn4/9.annotation/eggnog-mapper-new/eggnog-mapper/eggnogmapper/search.py", line 179, in iter_seq_hits
    fixed_Z=fixed_Z)
  File "/mnt/ls15/scratch/users/wilburn4/9.annotation/eggnog-mapper-new/eggnog-mapper/eggnogmapper/search.py", line 111, in scan_hits
    struct.unpack("7Q I 4x 3Q 3I 4x 6Q I 4x Q", alibit)
struct.error: unpack requires a string argument of length 168

**Question**
Should I use change anything in the command line or load some module on my cluster?  ...or what's going on?

**Comment by jhcepas** [comment]
does it happen with a specific amino acid sequence?
it looks the hmmer server is somehow not returning a match in the correct format...

**Comment by davidbio** [comment]
Related: #99

**Comment by sckb** [comment]
Exactly the same issue here but using  hmmer-3.1b2 instead of hmmer-3.2.1 solved the problem.
