### ISSUE TITLE
Python error, no output

### ISSUE THREAD

**Issue by pbravakos** [eggnogdb/eggnog-mapper#112]
I am trying to run eggnog mapper on a cluster but i get the following error
```
#  emapper-1.0.3
# ./emapper.py  --database gproNOG --hmm_maxseqlen 5000 --hmm_evalue 0.001 --override -i InterProScan_amino-acid-sequences.fasta --output emapper --temp_dir temp --cpu 20
/home1/pbravakos/Software/eggnog-mapper/data/hmmdb_levels/gproNOG_hmm/gproNOG_hmm.all_hmm
eggnog-mapper/data/hmmdb_levels/gproNOG_hmm/gproNOG_hmm.all_hmm
ESC[32mSequence mapping starts now!ESC[0m
Traceback (most recent call last):
  File "eggnog-mapper/emapper.py", line 1009, in <module>
    main(args)
  File "eggnog-mapper/emapper.py", line 226, in main
    dump_hmm_matches(args.input, hmm_hits_file, dbpath, port, scantype, idmap, args)
  File "eggnog-mapper/emapper.py", line 412, in dump_hmm_matches
    print >>OUT, '\t'.join([name] + ['-'] * (len(hits_header) - 1))
TypeError: sequence item 0: expected string, float found
```
If you have any idea on how to fix this, please tell me.
Thanks

**Comment by jhcepas** [comment]
we would need more data to debug (i.e. input file)
