### ISSUE TITLE
emapper.py subprocess.CalledProcessError

### ISSUE THREAD

**Issue by eli1199** [eggnogdb/eggnog-mapper#136]
Hello,

I am trying to run eggnon emapper.py on some proteins. I followed the instructions here: https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2 and downloaded it by cloning the git repo. 

To get the databases I did: `python download_eggnog_data.py`

Then I ran emapper.py using the following code: 
`python emapper.py -i prots.faa --output emapper_output -m diamond
`
It runs for ~20 minutes, then this comes up:

> Building reference index... Traceback (most recent call last):
>   File "emapper.py", line 1210, in <module>
>     main(args)
>   File "emapper.py", line 226, in main
>     dump_diamond_matches(args.input, seed_orthologs_file, args)
>   File "emapper.py", line 380, in dump_diamond_matches
>     raise e
> subprocess.CalledProcessError: Command returned non-zero exit status -9
> 

I also tried installing it by downloading and decompressing https://github.com/jhcepas/eggnog-mapper/releases but error still persists.

Any ideas on what could fix this?

**Comment by eli1199** [comment]
Turns out it was just a memory problem.
