### ISSUE TITLE
Error “Failed to allocate sufficient memory“，When i running eggnog-mapper in diamond mode

### ISSUE THREAD

**Issue by kmosi0** [eggnogdb/eggnog-mapper#141]
Hi everyone !
I running eggnog-mapper in diamond mode，my command is“./emapper.py -i peps.fasta --output cdna -d data/eggnog --cpu 20   -m diamond   ” 

My linux server  memory is 500G，but still insufficient.

A few minutes later，error occurs 
“Failed to allocate sufficient memory. Please refer to the readme for instructions on memory usage.
Traceback (most recent call last):
  File "./emapper.py", line 1001, in <module>
    main(args)
  File "./emapper.py", line 216, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "./emapper.py", line 353, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/home/zhan/biosoft/diamond/diamond blastp -d /home/zhan/biosoft/eggnog-mapper/eggnog-mapper-1.0.3/data/eggnog_proteins.dmnd -q /peps.fasta --more-sensitive --threads 20 -e 0.001000 -o /home/zhan/biosoft/eggnog-mapper/eggnog-mapper-1.0.3/emappertmp_dmdn_8tAlfl/e0713f57b66241df93c74ef0accf09c1 --top 3' returned non-zero exit status 1”

Wish for your reply ,thank you !

**Comment by kmosi0** [comment]
I solve it by "add  PATH to eggnog-mapper-1.0.3/bin",so it run diamond in eggnog-mapper-1.0.3/bin ,it worked !
