### ISSUE TITLE
problem eggnog 2.0.1 calling diamond

### ISSUE THREAD

**Issue by glucksfall** [eggnogdb/eggnog-mapper#172]
Hello @jhcepas 

We found recently that the last version is somehow incompatible with diamond (the binary at the bin folder and also the system binary installed with apt). It seems the error is about the use of the subject-cover option: `Error: Invalid option: subject-cover`. I "checkout" the clone to the branch "2.0.0" and it works perfectly. 

Best regards

```
emapper.py -i test/polb.fa -o . -d bact -m diamond
/usr/bin/diamond /shared/D2/opt/repositories/git-reps/eggnog-mapper.jhcepas
#  emapper-2.0.1
# ./emapper.py  -i test/polb.fa -o . -d bact -m diamond
  /usr/bin/diamond blastp -d /shared/D2/opt/repositories/git-reps/eggnog-mapper.jhcepas/data/eggnog_proteins.dmnd -q /shared/D2/opt/repositories/git-reps/eggnog-mapper.jhcepas/test/polb.fa --more-sensitive --threads 2 -e 0.001000 -o /shared/D2/opt/repositories/git-reps/eggnog-mapper.jhcepas/emappertmp_dmdn_1vFPpV/fe96870147e44821a9c5f7fb7ded2495 --top 3 --query-cover 0 --subject-cover 0
Error: Invalid option: subject-cover
Traceback (most recent call last):
  File "/opt/repositories/git-reps/eggnog-mapper.jhcepas/emapper.py", line 1213, in <module>
    main(args)
  File "/opt/repositories/git-reps/eggnog-mapper.jhcepas/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/opt/repositories/git-reps/eggnog-mapper.jhcepas/emapper.py", line 380, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/usr/bin/diamond blastp -d /shared/D2/opt/repositories/git-reps/eggnog-mapper.jhcepas/data/eggnog_proteins.dmnd -q /shared/D2/opt/repositories/git-reps/eggnog-mapper.jhcepas/test/polb.fa --more-sensitive --threads 2 -e 0.001000 -o /shared/D2/opt/repositories/git-reps/eggnog-mapper.jhcepas/emappertmp_dmdn_1vFPpV/fe96870147e44821a9c5f7fb7ded2495 --top 3 --query-cover 0 --subject-cover 0' returned non-zero exit status 1
```

**Comment by Cantalapiedra** [comment]
Hi,

I tried running the same command (without -d, which has no effect with -m diamond), and it runs for me. Maybe it is related with diamond version. I am using diamond version 0.9.24

Best,
Carlos

**Comment by Cantalapiedra** [comment]
If issue persists, please re-open or re-submit issue. Thank you
