### ISSUE TITLE
KeyError: 'biNOG'

### ISSUE THREAD

**Issue by carolhuaxia** [eggnogdb/eggnog-mapper#173]
I have download eggnog-mapper-2.0.1 and the database euk.
I run the test as follow:
```shell
python emapper.py -i test/p53.fa --output p53_maNOG -d euk --cpu 2 --override
```
and I got the error as follow:
```shell
/home/luohx/software/src/eggnog-mapper-2.0.1/bin/diamond /home/luohx/software/src/eggnog-mapper-2.0.1
#  emapper-2.0.1
# ./emapper.py  -i test/p53.fa --output p53_maNOG -d euk --cpu 2 --override
/home/luohx/software/src/eggnog-mapper-2.0.1/data/hmmdb_levels/euk_500/euk_500.hmm
Sequence mapping starts now!
 Processed queries:1 total_time:116.901343822 rate:0.01 q/s
Hit refinement starts now
 Processed queries:1 total_time:5.32965016365 rate:0.19 q/s
Reading HMM matches
Functional annotation of refined hits starts now
Traceback (most recent call last):
  File "emapper.py", line 620, in annotate_hit_line
    return _annotate_hit_line(arguments)
  File "emapper.py", line 650, in _annotate_hit_line
    match_levels.update(LEVEL_PARENTS[nog.split("@")[1]])
KeyError: 'biNOG'
Traceback (most recent call last):
  File "emapper.py", line 1213, in <module>
    main(args)
  File "emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "emapper.py", line 732, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/home/software/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
KeyError: 'biNOG'
```
How can I deal with this error. Thank you

**Comment by jhcepas** [comment]
version 2.x has no support for hmm databases. You should use diamond mode
and filter by taxonomic scope.
