### ISSUE TITLE
KeyError: 'bactNOG'

### ISSUE THREAD

**Issue by liufangbaishikele** [eggnogdb/eggnog-mapper#190]
Hi developer,

I have installed ``emapper-2.0.1-4-g2466c1b`` and downloaded all the associated database. I can run the first step to generate the ortholog file. However, when I run the next annotation step, it popped out below error. To make sure my ortholog output has no problem, I rerun the annotation step using the ortholog out from the emapper's /test/ folder

**CODE**
```
/mnt/m1/liufang/eggnog-mapper/emapper.py -m diamond  -o test_out_annotation --data_dir /mnt/m1/liufang/db/eggNog_mapperv2  --dmnd_db /mnt/m1/liufang/db/eggNog_mapperv2/eggnog_proteins.dmnd --annotate_hits_table test/test_output.emapper.seed_orthologs --override
```
**ERROR**

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/m1/liufang/eggnog-mapper/emapper.py", line 620, in annotate_hit_line
  File "/mnt/m1/liufang/eggnog-mapper/emapper.py", line 620, in annotate_hit_line
    return _annotate_hit_line(arguments)
  File "/mnt/m1/liufang/eggnog-mapper/emapper.py", line 650, in _annotate_hit_line
    return _annotate_hit_line(arguments)
    match_levels.update(LEVEL_PARENTS[nog.split("@")[1]])
  File "/mnt/m1/liufang/eggnog-mapper/emapper.py", line 650, in _annotate_hit_line
    match_levels.update(LEVEL_PARENTS[nog.split("@")[1]])
KeyError: 'bactNOG'
KeyError: 'bactNOG'
Traceback (most recent call last):
  File "/mnt/m1/liufang/eggnog-mapper/emapper.py", line 1213, in <module>
    main(args)
  File "/mnt/m1/liufang/eggnog-mapper/emapper.py", line 250, in main
    annotate_hits_file(args.annotate_hits_table, annot_file, hmm_hits_file, args)
  File "/mnt/m1/liufang/eggnog-mapper/emapper.py", line 732, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/conda/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
KeyError: 'bactNOG'
```
PS: when I run this step with my version ``emapper-2466c1b``, it worked without error. I am not good with python, no sure if it related to path problems or not. As a reference for this troubleshooting, I installed ``emapper-2.0.1-4-g2466c1b`` under the python2.7 environment.

Thanks for your time! Any thoughts will be really appreicated!

**Comment by Cantalapiedra** [comment]
Hi liufangbaishikele,

It works for me when running emapper-2.0.1-14-gbf04860:

./emapper.py -m diamond -o kk_borrar --annotate_hits_table tests/fixtures/test_output.emapper.seed_orthologs

Could it be related to the eggnogdb you are using?

Please, if you find these problems again re-submit the issue.

Thank you very much.

Best,
Carlos
