### ISSUE TITLE
Plesae, help me!!!  sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by chulghim** [eggnogdb/eggnog-mapper#212]
test command : ./emapper.py -m diamond -i tests/fixtures/test_queries.fa --data_dir tests/fixtures --output_dir tests/out -o test --override

I got the following error. 
......
Deallocating buffers...  [0s]
Deallocating queries...  [0s]
Loading query sequences...  [0s]
Closing the input file...  [0s]
Closing the output file...  [0s]
Closing the database file...  [0s]
Deallocating taxonomy...  [0s]
Total time = 3.289s
Reported 44 pairwise alignments, 44 HSPs.
2 queries aligned.
Traceback (most recent call last):
  File "./emapper.py", line 1213, in <module>
    main(args)
  File "./emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "./emapper.py", line 714, in annotate_hits_file
    seq2annotOG = annota.get_ogs_annotations(set([v[0] for v in seq2bestOG.itervalues()]))
  File "/mnt/lustre2/Gene_Biome/chul/eggnog-mapper/eggnogmapper/annota.py", line 37, in get_ogs_annotations
    if db.execute(cmd):
sqlite3.OperationalError: disk I/O error

**Comment by chulghim** [comment]
Oh. sorry.
sqlite doesn't work in network file system. 

I solved it as using local dist drive.
Thanks.
