### ISSUE TITLE
FASTA header causes crash

### ISSUE THREAD

**Issue by alimayy** [eggnogdb/eggnog-mapper#270]
Hi there

As far as I can see the following FASTA header format causes emapper to crash:

```
>5000_00002
MRVLKFGGTSVANAERFLRVADILESNARQGQVATVLSAPAKITNHLVAMIEKTISGQDALPNISDAERIFAELLTGLAA
AQPGFPLAQLKTFVDQEFAQIKHVLHGISLLGQCPDSINAALICRGEKMSIAIMAGVLEARGHNVTVIDPVEKLLAVGHY
LESTVDIAESTRRIAASRIPADHMVLMAGFTAGNEKGELVVLGRNGSDYSAAVLAACLRADCCEIWTDVDGVYTCDPRQV
PDARLLKSMSYQEAMELSYFGAKVLHPRTITPIAQFQIPCLIKNTGNPQAPGTLIGASRDEDELPVKGISNLNNMAMFSV
SGPGMKGMVGMAARVFAAMSRARISVVLITQSSSEYSISFCVPQSDCVRAERAMQEEFYLELKEGLLEPLAVTERLAIIS
VVGDGMRTLRGISAKFFAALARANINIVAIAQGSSERSISVVVNNDDATTGVRVTHQMLFNTDQVIEVFVIGVGGVGGAL
LEQLKRQQSWLKNKHIDLRVCGVANSKALLTNVHGLNLENWQEELAQAKEPFNLGRLIRLVKEYHLLNPVIVDCTSSQAV
ADQYADFLREGFHVVTPNKKANTSSMDYYHQLRYAAEKSRRKFLYDTNVGAGLPVIENLQNLLNAGDELMKFSGILSGSL
SYIFGKLDEGMSFSEATTLAREMGYTEPDPRDDLSGMDVARKLLILARETGRELELADIEIEPVLPAEFNAEGDVAAFMA
NLSQLDDLFAARVAKARDEGKVLRYVGNIDEDGVCRVKIAEVDGNDPLFKVKNGENALAFYSHYYQPLPLVLRGYGAGND
VTAAGVFADLLRTLSWKLGV
```
The emapper version and the command used can be found below:

```
python3.8 ~/packages/eggnog-mapper-refactor/eggnog-mapper/emapper.py -i test.fasta --itype proteins -o out -m diamond --data_dir /dev/shm/emapper_refactor/data/ --dmnd_db /dev/shm/emapper_refactor/data/eggnog_proteins.dmnd --pfam_realign denovo --cpu 32 --target_orthologs all --scratch_dir /scratch/eggnogmapper --query_cover 0
#  emapper-2.0.2-rf1-122-g70be7ae
# emapper.py  -i test.fasta --itype proteins -o out -m diamond --data_dir /dev/shm/emapper_refactor/data/ --dmnd_db /dev/shm/emapper_refactor/data/eggnog_proteins.dmnd --pfam_realign denovo --cpu 32 --target_orthologs all --scratch_dir /scratch/eggnogmapper --query_cover 0
  /home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/bin/diamond blastp -d /dev/shm/emapper_refactor/data/eggnog_proteins.dmnd -q /home/ali/temp/testemapper/test.fasta --threads 32 -e 0.001 -o /home/ali/temp/testemapper/emappertmp_dmdn_6yuxtbky/007c04025c0f45ad89a86d7b31fd8f7d --query-cover 0.0 --subject-cover 0 --top 3
Functional annotation of refined hits starts now
 Processed queries:2 total_time:0.10067319869995117 rate:19.87 q/s
de novo scan of PFAM domains
Traceback (most recent call last):
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/emapper.py", line 566, in <module>
    emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/emapper.py", line 241, in run
    self.annotate(args, annotate_hits_table, cache_dir)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/emapper.py", line 219, in annotate
    annotator.annotate(annot_in,
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/annotation/annotator.py", line 111, in annotate
    all_orthologs, all_annotations, qn, elapsed_time = self._annotate(seed_orthologs_file, pfam_file)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/annotation/annotator.py", line 296, in _annotate
    all_annotations = run_pfam_mode(self.pfam_realign, all_annotations, self.queries_fasta, self.translate, self.cpu, self.temp_dir, pfam_file)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/annotation/pfam/pfam_modes.py", line 26, in run_pfam_mode
    aligned_pfams = pfam_align_denovo(all_annotations, queries_fasta, translate, cpu, temp_dir, pfam_file)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/annotation/pfam/pfam_denovo.py", line 20, in pfam_align_denovo
    pfam_aligner.align_whole_pfam(infile, pfam_file, silent = True)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/annotation/pfam/pfam.py", line 292, in align_whole_pfam
    s.search_hmm_matches(infile, pfam_file, silent)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/search/hmmer/hmmer.py", line 126, in search_hmm_matches
    self.dump_hmm_matches(in_file, hmm_hits_file, dbpath, port, hosts, idmap_file, silent)
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/search/hmmer/hmmer.py", line 226, in dump_hmm_matches
    for name, elapsed, hits, querylen, seq in iter_hits(in_file,
  File "/home/ali/packages/eggnog-mapper-refactor/eggnog-mapper/eggnogmapper/search/hmmer/hmmer_search.py", line 295, in hmmcommand
    qlen = queries_dict[query]
KeyError: 500000002.0


```

**Comment by Cantalapiedra** [comment]
Hi @alimayy ,

thank you very much for reporting this.

Best,
Carlos
