### ISSUE TITLE
Version 2.0.8: ModuleNotFoundError: No module named 'eggnogmapper.deco'

### ISSUE THREAD

**Issue by lukasjelonek** [eggnogdb/eggnog-mapper#280]
I installed it with pip. It seems that the directory `eggnogmapper/deco/` is missing the `__init__.py` to be identified as a package (and included in the pip package).

```
> emapper.py
Traceback (most recent call last):
  File "[...]/bin/emapper.py", line 14, in <module>
    from eggnogmapper.emapper import Emapper
  File "[...]/lib/python3.7/site-packages/eggnogmapper/emapper.py", line 16, in <module>
    from .deco.decoration import run_gff_decoration, DECORATE_GFF_NONE
```

**Comment by Cantalapiedra** [comment]
I yanked the pip package. Thank you!

**Comment by Cantalapiedra** [comment]
https://pypi.org/project/eggnog-mapper/2.0.8.post2/
