### ISSUE TITLE
Missing module?

### ISSUE THREAD

**Issue by tnn111** [eggnogdb/eggnog-mapper#284]
When I run eggmapper, as

/usr/bin/time emapper.py --decorate_gff no --usemem --cpu 0 --query-cover 70 --subject-cover 70 -i xaa.faa --output xaa &> xaa.log

I get the following error. Any idea as to what I'm doing wrong?

Thanks!

Traceback (most recent call last):
  File "/global/homes/t/torben/opt/anaconda3/bin/emapper.py", line 4, in <module>
    __import__('pkg_resources').run_script('eggnog-mapper==2.0.8', 'emapper.py')
  File "/global/homes/t/torben/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/homes/t/torben/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/global/u1/t/torben/opt/anaconda3/lib/python3.7/site-packages/eggnog_mapper-2.0.8-py3.7.egg/EGG-INFO/scripts/emapper.py", line 14, in <module>
    from eggnogmapper.emapper import Emapper
  File "/global/u1/t/torben/opt/anaconda3/lib/python3.7/site-packages/eggnog_mapper-2.0.8-py3.7.egg/eggnogmapper/emapper.py", line 16, in <module>
    from .deco.decoration import run_gff_decoration, DECORATE_GFF_NONE
ModuleNotFoundError: No module named 'eggnogmapper.deco'
Command exited with non-zero status 1
0.59user 0.59system 1:02.50elapsed 1%CPU (0avgtext+0avgdata 21124maxresident)k
0inputs+0outputs (0major+5298minor)pagefaults 0swaps

**Comment by Cantalapiedra** [comment]
Hi @tnn111 ,

when did you download eggnog-mapper?
I thought this had been fixed #280 

It should also be fixed in the master branch.

Best,
Carlos

**Comment by tnn111** [comment]
Hi, I downloaded 2.0.8 yesterday. It was the tar.gz file.

**Comment by Cantalapiedra** [comment]
Hi @tnn111 ,

Sorry, I thought you were using the pypi version.
I also didn't fix the github release properly.
I tried again, and I hope that the Release is now fine.

Best,
Carlos

**Comment by Jiulong-Zhao** [comment]
> Hi @tnn111 ,
> 
> Sorry, I thought you were using the pypi version.
> I also didn't fix the github release properly.
> I tried again, and I hope that the Release is now fine.
> 
> Best,
> Carlos

@Cantalapiedra Hi!
I installed the eggnog-mapper v2.0.8 by conda a few days ago and also meet the same problem:

Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/eggnogg-mapper/bin/emapper.py", line 4, in <module>
    __import__('pkg_resources').run_script('eggnog-mapper==2.0.8', 'emapper.py')
  File "/home/mcs/miniconda3/envs/eggnogg-mapper/lib/python3.7/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mcs/miniconda3/envs/eggnogg-mapper/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/mcs/miniconda3/envs/eggnogg-mapper/lib/python3.7/site-packages/eggnog_mapper-2.0.8-py3.7.egg/EGG-INFO/scripts/emapper.py", line 14, in <module>
    from eggnogmapper.emapper import Emapper
  File "/home/mcs/miniconda3/envs/eggnogg-mapper/lib/python3.7/site-packages/eggnog_mapper-2.0.8-py3.7.egg/eggnogmapper/emapper.py", line 16, in <module>
    from .deco.decoration import run_gff_decoration, DECORATE_GFF_NONE
ModuleNotFoundError: No module named 'eggnogmapper.deco'

So how should I solve this problem? I am a beginner of Linux and really appreciate the detailed approach!

Thank you so much!

**Comment by Cantalapiedra** [comment]
Upgrading to version 2.1.0 should resolve this issue

Please, re-open if it is not the case.

Best,
Carlos
