### ISSUE TITLE
sqlite3.DatabaseError

### ISSUE THREAD

**Issue by 123chenshixin** [eggnogdb/eggnog-mapper#291]
Hi @Cantalapiedra,
I am trying to annotate my own-assblemed fungus genome by using eggnog-mapper tool.
However,I get something wrong throught command belows.
`emapper.py -i  ../GL.pp.fa -o GL  --usemem --cpu 0`
The error I get is as follows.
> ^[[1;32mFuncional annotation of hits...^[[0m
0 2.1457672119140625e-06 0.00 q/s (% mem usage: 1.90, % mem avail: 98.13)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/cxs3_z4/software/Python-3.9.0/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cxs3_z4/software/eggnog-mapper-2.1.0-1/eggnogmapper/annotation/annotator_worker.py", line 29, in annotate_hit_line_ondisk
    eggnog_db = get_eggnog_db(usemem = False)
  File "/home/cxs3_z4/software/eggnog-mapper-2.1.0-1/eggnogmapper/annotation/db_sqlite.py", line 13, in get_eggnog_db
    db = AnnotDB(usemem)
  File "/home/cxs3_z4/software/eggnog-mapper-2.1.0-1/eggnogmapper/annotation/db_sqlite.py", line 39, in __init__
    curs.execute("PRAGMA synchronous=OFF;")
sqlite3.DatabaseError: malformed database schema (prots) - near "WITHOUT": syntax error
"""

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "/home/cxs3_z4/software/eggnog-mapper-2.1.0-1/eggnogmapper/annotation/annotator.py", line 227, in _annotate_ondisk
    for result in pool.imap(annotate_hit_line_ondisk,
  File "/home/cxs3_z4/software/Python-3.9.0/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
sqlite3.DatabaseError: malformed database schema (prots) - near "WITHOUT": syntax error

It would be highly appreciated  if you point out the problem and give me some help!

**Comment by Cantalapiedra** [comment]
Hi @123chenshixin ,

Could you paste the output from `emapper.py --version`? It could be a problem with DB version, I am not sure.
Besides that, note that `--usemem` will have no effect unless using `-m hmmer` (you are using, by default, `-m diamond`).

Best,
Carlos

**Comment by 123chenshixin** [comment]
The  output are as follows. 

> [cxs3_z4@node1 ~]$ emapper.py  --version
There was an error retrieving eggnog-mapper DB data: malformed database schema (prots) - near "WITHOUT": syntax error
Maybe you need to run download_eggnog_data.py
emapper-2.1.0-1 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1

Then I try to run download_eggnog_data. py and get the following information. 

> [cxs3_z4@node1 ~]$ download_eggnog_data.py
Skipping eggnog.db database (already present). Use -f to force download
Skipping eggnog.taxa.db database (already present). Use -f to force download
Skipping diamond database (or already present). Use -f to force download
Skipping Pfam database (or already present). Use -P and -f to force download
Skipping MMseqs2 database (or already present). Use -M and -f to force download
No HMMER database requested. Use "-H -d taxid" to download the hmmer database for taxid
Finished.

**Comment by Gu2uMo** [comment]
I met a similar problem, and I use the same version of emapper and eggnog database, except my diamond version is 2.0.5 (but seems it doesn't matter
1. I want to annotate my protein seqs
```bash
sample='Mariana_3-5'
thread='39'
db_path=eggNOG
eggnog-mapper-2.1.0-1/emapper.py \
        --cpu ${thread} -i ../04_gene/${sample}_04_gene_prodigal.faa \
        -m diamond --data_dir ${db_path} \
        --query_cover 70 --subject_cover 70 \
        --evalue 0.00001 --score 60 --sensmode ultra-sensitive \
        --pident 30 -o ${sample}_05_05_eggnog 
```
but only get the 'hits' file. Both 'seed_orthologs' and 'annotations' are empty. 

2.  Then I try the annotation function with the hits file by 
```bash
emapper.py -m no_search --annotate_hits_table test.input -o out_test --cpu 4 --data_dir eggNOG
```
Got the similar error, it reminds  
```txt
Error: annotation went wrong for hit ['sample_0_2', '1121912.AUHD01000002_gene3295', 5.6e-164, 583.6]. no such table: prots
```
Though I cut the hits file to 4 columns "query, hit, evalue, score", it still failed 

Any advice should I try? 

Thanks

**Comment by Cantalapiedra** [comment]
> The output are as follows.
> 
> > [cxs3_z4@node1 ~]$ emapper.py  --version
> > There was an error retrieving eggnog-mapper DB data: malformed database schema (prots) - near "WITHOUT": syntax error
> > Maybe you need to run download_eggnog_data.py
> > emapper-2.1.0-1 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1
> 
> Then I try to run download_eggnog_data. py and get the following information.
> 
> > [cxs3_z4@node1 ~]$ download_eggnog_data.py
> > Skipping eggnog.db database (already present). Use -f to force download
> > Skipping eggnog.taxa.db database (already present). Use -f to force download
> > Skipping diamond database (or already present). Use -f to force download
> > Skipping Pfam database (or already present). Use -P and -f to force download
> > Skipping MMseqs2 database (or already present). Use -M and -f to force download
> > No HMMER database requested. Use "-H -d taxid" to download the hmmer database for taxid
> > Finished.

I cannot reproduce the error myself. I am using sqlite 3.30.1
`sqlite3 --version`

I guess that your eggnog.db is within the "data" folder. What happens if you type:

`sqlite3 data/eggnog.db ".schema"`

also

`sqlite3 data/eggnog.db "select * from version"`

you should get "5.0.2" as output.

**Comment by Cantalapiedra** [comment]
> I met a similar problem, and I use the same version of emapper and eggnog database, except my diamond version is 2.0.5 (but seems it doesn't matter
> 
> 1. I want to annotate my protein seqs
> 
> ```shell
> sample='Mariana_3-5'
> thread='39'
> db_path=eggNOG
> eggnog-mapper-2.1.0-1/emapper.py \
>         --cpu ${thread} -i ../04_gene/${sample}_04_gene_prodigal.faa \
>         -m diamond --data_dir ${db_path} \
>         --query_cover 70 --subject_cover 70 \
>         --evalue 0.00001 --score 60 --sensmode ultra-sensitive \
>         --pident 30 -o ${sample}_05_05_eggnog 
> ```
> 
> but only get the 'hits' file. Both 'seed_orthologs' and 'annotations' are empty.
> 
> 1. Then I try the annotation function with the hits file by
> 
> ```shell
> emapper.py -m no_search --annotate_hits_table test.input -o out_test --cpu 4 --data_dir eggNOG
> ```
> 
> Got the similar error, it reminds
> 
> ```
> Error: annotation went wrong for hit ['sample_0_2', '1121912.AUHD01000002_gene3295', 5.6e-164, 583.6]. no such table: prots
> ```
> 
> Though I cut the hits file to 4 columns "query, hit, evalue, score", it still failed
> 
> Any advice should I try?
> 
> Thanks

Hi @Gu2uMo ,

what is the output of `emapper.py --version` in your case?

Thank you

Carlos

**Comment by Gu2uMo** [comment]
> > I met a similar problem, and I use the same version of emapper and eggnog database, except my diamond version is 2.0.5 (but seems it doesn't matter
> > 
> > 1. I want to annotate my protein seqs
> > 
> > ```shell
> > sample='Mariana_3-5'
> > thread='39'
> > db_path=eggNOG
> > eggnog-mapper-2.1.0-1/emapper.py \
> >         --cpu ${thread} -i ../04_gene/${sample}_04_gene_prodigal.faa \
> >         -m diamond --data_dir ${db_path} \
> >         --query_cover 70 --subject_cover 70 \
> >         --evalue 0.00001 --score 60 --sensmode ultra-sensitive \
> >         --pident 30 -o ${sample}_05_05_eggnog 
> > ```
> > 
> > 
> > but only get the 'hits' file. Both 'seed_orthologs' and 'annotations' are empty.
> > 
> > 1. Then I try the annotation function with the hits file by
> > 
> > ```shell
> > emapper.py -m no_search --annotate_hits_table test.input -o out_test --cpu 4 --data_dir eggNOG
> > ```
> > 
> > 
> > Got the similar error, it reminds
> > ```
> > Error: annotation went wrong for hit ['sample_0_2', '1121912.AUHD01000002_gene3295', 5.6e-164, 583.6]. no such table: prots
> > ```
> > 
> > 
> > Though I cut the hits file to 4 columns "query, hit, evalue, score", it still failed
> > Any advice should I try?
> > Thanks
> 
> Hi @Gu2uMo ,
> 
> what is the output of `emapper.py --version` in your case?
> 
> Thank you
> 
> Carlos

I change my diamond version and try again (didn't work), now is 
```bash
eggnog-mapper-2.1.0-1/emapper.py --version

emapper-2.1.0-1 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1
```

**Comment by Cantalapiedra** [comment]
> > > I met a similar problem, and I use the same version of emapper and eggnog database, except my diamond version is 2.0.5 (but seems it doesn't matter
> > > 
> > > 1. I want to annotate my protein seqs
> > > 
> > > ```shell
> > > sample='Mariana_3-5'
> > > thread='39'
> > > db_path=eggNOG
> > > eggnog-mapper-2.1.0-1/emapper.py \
> > >         --cpu ${thread} -i ../04_gene/${sample}_04_gene_prodigal.faa \
> > >         -m diamond --data_dir ${db_path} \
> > >         --query_cover 70 --subject_cover 70 \
> > >         --evalue 0.00001 --score 60 --sensmode ultra-sensitive \
> > >         --pident 30 -o ${sample}_05_05_eggnog 
> > > ```
> > > 
> > > 
> > > but only get the 'hits' file. Both 'seed_orthologs' and 'annotations' are empty.
> > > 
> > > 1. Then I try the annotation function with the hits file by
> > > 
> > > ```shell
> > > emapper.py -m no_search --annotate_hits_table test.input -o out_test --cpu 4 --data_dir eggNOG
> > > ```
> > > 
> > > 
> > > Got the similar error, it reminds
> > > ```
> > > Error: annotation went wrong for hit ['sample_0_2', '1121912.AUHD01000002_gene3295', 5.6e-164, 583.6]. no such table: prots
> > > ```
> > > 
> > > 
> > > Though I cut the hits file to 4 columns "query, hit, evalue, score", it still failed
> > > Any advice should I try?
> > > Thanks
> > 
> > 
> > Hi @Gu2uMo ,
> > what is the output of `emapper.py --version` in your case?
> > Thank you
> > Carlos
> 
> I change my diamond version and try again (didn't work), now is
> 
> ```shell
> eggnog-mapper-2.1.0-1/emapper.py --version
> 
> emapper-2.1.0-1 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1
> ```

Your database (eggnog.db) is within "data/" or within "eggNOG/"?

**Comment by Gu2uMo** [comment]
> > > > I met a similar problem, and I use the same version of emapper and eggnog database, except my diamond version is 2.0.5 (but seems it doesn't matter
> > > > 
> > > > 1. I want to annotate my protein seqs
> > > > 
> > > > ```shell
> > > > sample='Mariana_3-5'
> > > > thread='39'
> > > > db_path=eggNOG
> > > > eggnog-mapper-2.1.0-1/emapper.py \
> > > >         --cpu ${thread} -i ../04_gene/${sample}_04_gene_prodigal.faa \
> > > >         -m diamond --data_dir ${db_path} \
> > > >         --query_cover 70 --subject_cover 70 \
> > > >         --evalue 0.00001 --score 60 --sensmode ultra-sensitive \
> > > >         --pident 30 -o ${sample}_05_05_eggnog 
> > > > ```
> > > > 
> > > > 
> > > > but only get the 'hits' file. Both 'seed_orthologs' and 'annotations' are empty.
> > > > 
> > > > 1. Then I try the annotation function with the hits file by
> > > > 
> > > > ```shell
> > > > emapper.py -m no_search --annotate_hits_table test.input -o out_test --cpu 4 --data_dir eggNOG
> > > > ```
> > > > 
> > > > 
> > > > Got the similar error, it reminds
> > > > ```
> > > > Error: annotation went wrong for hit ['sample_0_2', '1121912.AUHD01000002_gene3295', 5.6e-164, 583.6]. no such table: prots
> > > > ```
> > > > 
> > > > 
> > > > Though I cut the hits file to 4 columns "query, hit, evalue, score", it still failed
> > > > Any advice should I try?
> > > > Thanks
> > > 
> > > 
> > > Hi @Gu2uMo ,
> > > what is the output of `emapper.py --version` in your case?
> > > Thank you
> > > Carlos
> > 
> > 
> > I change my diamond version and try again (didn't work), now is
> > ```shell
> > eggnog-mapper-2.1.0-1/emapper.py --version
> > 
> > emapper-2.1.0-1 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1
> > ```
> 
> Your database (eggnog.db) is within "data/" or within "eggNOG/"?

Yes, but I give the path in the parameter "--data_dir". Now I solve it as you mention the sqlite version. Thanks !!!
I try it as below with "python=3.7.6" and "sqlite 3.30.1", as python=3.9 -> sqlite[version='>=3.33.0,<4.0a0|>=3.34.0,<4.0a0']
```bash
eggnog-mapper-2.1.0-1/emapper.py -m no_search --annotate_hits_table test.input -o out_test --cpu 4 --data_dir eggNOG --override
#  emapper-2.1.0-1
# emapper.py  -m no_search --annotate_hits_table test.input -o out_test --cpu 4 --data_dir /lustre/home/acct-ioozy/ioozy/Database/eggNOG_5.0.2 --override
Funcional annotation of hits...
0 2.1457672119140625e-06 0.00 q/s (% mem usage: 10.60, % mem avail: 89.35)
25 3.955089807510376 6.32 q/s (% mem usage: 10.70, % mem avail: 89.35)
Done
   /lustre/home/acct-ioozy/ioozy-user2/LYX/Project_Trench/05_annotation/05_eggnog/out_test.emapper.annotations

================================================================================
CITATION:
If you use this software, please cite:

[1] Fast genome-wide functional annotation through orthology assignment by
      eggNOG-mapper. Jaime Huerta-Cepas, Kristoffer Forslund, Luis Pedro Coelho,
      Damian Szklarczyk, Lars Juhl Jensen, Christian von Mering and Peer Bork.
      Mol Biol Evol (2017). doi: https://doi.org/10.1093/molbev/msx148

[2] eggNOG 5.0: a hierarchical, functionally and phylogenetically annotated
      orthology resource based on 5090 organisms and 2502 viruses. Jaime
      Huerta-Cepas, Damian Szklarczyk, Davide Heller, Ana Hernandez-Plaza,
      Sofia K Forslund, Helen Cook, Daniel R Mende, Ivica Letunic, Thomas
      Rattei, Lars J Jensen, Christian von Mering and Peer Bork. Nucleic Acids
      Research, Volume 47, Issue D1, 8 January 2019, Pages D309-D314,
      https://doi.org/10.1093/nar/gky1085 
e.g. Functional annotation was performed using emapper-2.1.0-1 [1]
 based on eggNOG orthology data [2]. Sequence searches were performed using [3].


================================================================================

Total hits processed: 25
Total time: 4 secs
FINISHED
```
Thanks a lot and maybe you should mention that in WIKI. 
or would you provide a yml file for the conda env you use, just like QIIME2?

**Comment by Cantalapiedra** [comment]
In light of the previous, maybe @123chenshixin could try to update the sqlite version, or downgrade to a version of python 3.8 just to be sure.

**Comment by 123chenshixin** [comment]
I follow your advise.And output something like this.

> [cxs3_z4@node1 eggnog-mapper-2.1.0-1]$ sqlite3 data/eggnog.db ".schema"
CREATE TABLE event(
i INTEGER PRIMARY KEY,
level VARCHAR(16),
og VARCHAR(16),
side1 TEXT,
side2 TEXT);
CREATE TABLE IF NOT EXISTS "og"(og VARCHAR(16), level VARCHAR(16), nm INTEGER, description TEXT, COG_categories VARCHAR(8), PRIMARY KEY (og, level)) without rowid;
CREATE TABLE IF NOT EXISTS "version" (version VARCHAR(16) PRIMARY KEY) without rowid;
CREATE TABLE IF NOT EXISTS "prots" (name VARCHAR(32) PRIMARY KEY, bigg_reaction VARCHAR(32), gos TEXT, pfam TEXT, pname VARCHAR(32), ogs VARCHAR(256), orthoindex VARCHAR(256), kegg_ko VARCHAR(256), kegg_cog VARCHAR(256), kegg_disease VARCHAR(256), kegg_ec VARCHAR(256), kegg_brite VARCHAR(256), kegg_rclass VARCHAR(256), kegg_tc VARCHAR(256), kegg_cazy VARCHAR(256), kegg_pathway VARCHAR(256), kegg_module VARCHAR(256), kegg_reaction VARCHAR(256), kegg_go VARCHAR(256), kegg_drug VARCHAR(256), kegg_pubmed TEXT, kegg_network TEXT) WITHOUT ROWID;
CREATE INDEX event_level_idx ON event (i, level);


> [cxs3_z4@node1 eggnog-mapper-2.1.0-1]$ sqlite3 data/eggnog.db "select * from version"
5.0.2

**Comment by Cantalapiedra** [comment]
Hi @123chenshixin ,

so the DB is the right one and sqlite3 is working fine with it. Maybe you should try updating or downgrading the python sqlite package version as @Gu2uMo did.

As I said above sqlite 3.35.2 was working for me with python 3.9; and sqlite 3.30.1 seems to work fine with python 3.7 and 3.8.

Depending on the environment you are working in you could try something similar to this (example using conda):
conda update sqlite
conda install sqlite=3.35.2
conda install sqlite=3.30.1

Best,
Carlos

**Comment by 123chenshixin** [comment]
My python version is  3.9.0. And I try to run with sqlite3 by the version of both 3.35.2 and 3.34.0. But it doesn't work.

**Comment by 123chenshixin** [comment]
I try to take your advise for updating and installing sqlite. But I also get the same wrong information.

> conda update sqlite
conda install sqlite=3.35.2

> emapper.py -m no_search --annotate_hits_table GL.emapper.seed_orthologs -o GL --cpu 10 --override
sqlite3.DatabaseError: malformed database schema (prots) - near "WITHOUT": syntax error
Error: annotation failed. malformed database schema (prots) - near "WITHOUT": syntax error

**Comment by 123chenshixin** [comment]
My python version is 3.9.0.

**Comment by 123chenshixin** [comment]
Then I try to downgrade python. For me, I use ` conda create -n egg python=**3.7**` to create a virtual enviornment and activate it. Then I type `pip install psutil`  because psutil module is required.
After doing this, I try to re-run the command above. Then it ran well and got the GL.emapper.annotations file which has 93 lines.
The version of sqlite3 I used is **3.35.2**.

> #  emapper-2.1.0-1
# emapper.py  -m no_search --annotate_hits_table GL.emapper.seed_orthologs -o GL --cpu 10 --override
Funcional annotation of hits...
0 1.430511474609375e-06 0.00 q/s (% mem usage: 8.40, % mem avail: 91.62)
93 28.73546075820923 3.24 q/s (% mem usage: 8.40, % mem avail: 91.62)
Done
   /home/cxs3_z4/20210312/whfs-xs-210078/GL-whfs-xs-210078_DNA_PacBio/GL_1/ccs/annotation/egg/GL.emapper.annotations

================================================================================
CITATION:
If you use this software, please cite:

[1] Fast genome-wide functional annotation through orthology assignment by
      eggNOG-mapper. Jaime Huerta-Cepas, Kristoffer Forslund, Luis Pedro Coelho,
      Damian Szklarczyk, Lars Juhl Jensen, Christian von Mering and Peer Bork.
      Mol Biol Evol (2017). doi: https://doi.org/10.1093/molbev/msx148

[2] eggNOG 5.0: a hierarchical, functionally and phylogenetically annotated
      orthology resource based on 5090 organisms and 2502 viruses. Jaime
      Huerta-Cepas, Damian Szklarczyk, Davide Heller, Ana Hernandez-Plaza,
      Sofia K Forslund, Helen Cook, Daniel R Mende, Ivica Letunic, Thomas
      Rattei, Lars J Jensen, Christian von Mering and Peer Bork. Nucleic Acids
      Research, Volume 47, Issue D1, 8 January 2019, Pages D309-D314,
      https://doi.org/10.1093/nar/gky1085
e.g. Functional annotation was performed using emapper-2.1.0-1 [1]
 based on eggNOG orthology data [2]. Sequence searches were performed using [3].


================================================================================

Total hits processed: 93
Total time: 29 secs
FINISHED

I don't know why in this way I can run it successfully. It seems so strange.

**Comment by Cantalapiedra** [comment]
Hi @123chenshixin ,

I am not sure why. Maybe some specific versions of sqlite + python?
Glad that you solved it at least!

Best,
Carlos

**Comment by 123chenshixin** [comment]
@Cantalapiedra ,
OK. Anyway thank you so much for providing a body of useful advice!

**Comment by duboism** [comment]
Hello,

I have a similar issue. My environment is:
  - Python 3.7.6
  - sqlite3 3.6.20

I'm a bit lost in the thread. How did you resolved it ?

**Comment by 123chenshixin** [comment]
> Hello,
> 
> I have a similar issue. My environment is:
> 
> * Python 3.7.6
> * sqlite3 3.6.20
> 
> I'm a bit lost in the thread. How did you resolved it ?

Hello,
Maybe you can downgrade your sqlite3 version. As for me, I use 3.35.2. You can try `conda install sqlite=3.35.2`.

**Comment by duboism** [comment]
I think I know why it doesn't work in my case: the schema for the tables `prots` and maybe others uses the [`WITHOUT ROWID`](https://www.sqlite.org/withoutrowid.html) clause which was introduced in SQLite version `3.8.2` (I have a very old version: `3.6.20`).

It is still not clear if and why it doesn't work for `3.35.2`.

I was not aware that the `sqlite` databases are downloaded by `download_eggnog_data.py`. Therefore I think that the installer should check if the version of `sqlite` is compatible with the one used to create them.

**Comment by Cantalapiedra** [comment]
Hi @duboism ,

it would be great to know which versions are compatible, but I don't know how to assess this in a fast way.
There are many sqlite versions which I have no time to test.
I agree that would nice to be able to at least specify this in the documentation though.

Were you able to run it finally?

**Comment by duboism** [comment]
Hi @Cantalapiedra ,

I agree this is a hard task but at least `sqlite >= 3.8.2` is needed.

I will (try to) test this version in order to improve the lower bound.

**Comment by Cantalapiedra** [comment]
Hi @duboism ,

I guess I can update the wiki documentation with that "at least".

Thank you very much.

**Comment by duboism** [comment]
Version 3.8.2 seems to be OK: I installed it, downloaded the data and `emaper.py --version` works. I also tested that it can open the `eggnog.db` file.

**Comment by duboism** [comment]
Version 3.35.2 seems OK too.

**Comment by Cantalapiedra** [comment]
ty @duboism !

**Comment by davised** [comment]
folks on centos 7 still will be running into this issue. The last centos 7 sqlite3 version is 3.7.17.

I'll try to install under a conda env to see if I can resolve the issue.

The strange thing is that running `sqlite3 data/eggnog.db "select * from version"` does return `5.0.2`.

**Comment by davised** [comment]
Installing sqlite3 in the conda env didn't seem to work:

```
$ sqlite3 eggnog.db "select * from version"
5.0.2
$ sqlite3 --version
3.35.2 2021-03-17 19:07:21 ea80f3002f4120f5dcee76e8779dfdc88e1e096c5cdd06904c20fd26d50c3827
$ emapper.py --version
There was an error retrieving eggnog-mapper DB data: malformed database schema (prots) - near "WITHOUT": syntax error
Maybe you need to run download_eggnog_data.py
emapper-2.1.5 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Local diamond version: diamond version 2.0.11 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1
```

I supplied the path using the env vir:

```
$ echo $EGGNOG_DATA_DIR/
/nfs1/CGRB/databases/eggnog/
```

Which seems to be found by the `download_eggnog_data.py` script. Any other thoughts on how to resolve?

**Comment by Cantalapiedra** [comment]
Hi @davised ,

I am running it on Centos 7 right now.
I am using a conda environment with python 3.9.6, sqlite 3.36.0, eggnog-mapper 2.1.5.
Maybe you could try a similar environment.

**Comment by hahahaL** [comment]
suggest to check out that wheather your python-sqlite has used the update DB-version
The command is :
python 
  import sqlite3
  print(sqlite3.sqlite_version)

**Comment by TakashiKoyama** [comment]
I found solution for CentOS7 users.
Because CentOS7 users should install sqlite(>=3.8.2) from source, CentOS7 users need to set
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/sqlite3/lib
```
