### ISSUE TITLE
eggNOG mapping stopping at functional annotation

### ISSUE THREAD

**Issue by ddifraia** [eggnogdb/eggnog-mapper#307]
Dear members of the eggNOG teams,
I have a problem figuring out why my eggNOG program is not working properly...
Having a look , seems to be very related to this :  #299 
My current version is this one
`ddifraia:~/eggNOG> emapper.py --version
emapper-2.1.3 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1`

But when I run the eggNOG mapper, even with one single fasta sequence I get this strange error

` emapper.py  --cpu 4 -m diamond -i drerio_sub_fasta.fasta -o new_test
  /gsc/biosw/src/eggnog_mapper/bin/diamond blastp -d /misc/lapras/biodb/EGGNOG/eggnog_proteins.dmnd -q /home/lakatos/ddifraia/eggNOG/drerio_sub_fasta.fasta --threads 4 -o /home/lakatos/ddifraia/eggNOG/new_test.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
**Funcional annotation of hits...
0 2.384185791015625e-06 0.00 q/s (% mem usage: 24.10, % mem avail: 75.90)**
Traceback (most recent call last):
  File "/misc/leiron/biosw/src/python-3.7.2/lib/python3.7/site-packages/eggnog_mapper-2.1.3-py3.7.egg/EGG-INFO/scripts/emapper.py", line 665, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/misc/leiron/biosw/src/python-3.7.2/lib/python3.7/site-packages/eggnog_mapper-2.1.3-py3.7.egg/eggnogmapper/emapper.py", line 324, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "/misc/leiron/biosw/src/python-3.7.2/lib/python3.7/site-packages/eggnog_mapper-2.1.3-py3.7.egg/eggnogmapper/emapper.py", line 262, in run_generator
    for item in generator:
  File "/misc/leiron/biosw/src/python-3.7.2/lib/python3.7/site-packages/eggnog_mapper-2.1.3-py3.7.egg/eggnogmapper/annotation/annotator.py", line 300, in unpack_annotations
    for (hit, annotation), skip in annots:
  File "/misc/leiron/biosw/src/python-3.7.2/lib/python3.7/site-packages/eggnog_mapper-2.1.3-py3.7.egg/eggnogmapper/annotation/output.py", line 146, in output_annotations
    for (hit, annotation), exists in annots:
  File "/misc/leiron/biosw/src/python-3.7.2/lib/python3.7/site-packages/eggnog_mapper-2.1.3-py3.7.egg/eggnogmapper/annotation/annotator.py", line 242, in _annotate_ondisk
    pool = multiprocessing.Pool(self.cpu)
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/gsc/biosw/src/python3/lib/python3.7/multiprocessing/spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'` 

From this error I can see that it starts the functional annotation and then it crashes with this python error:
`emapper.py  --cpu 4 -m diamond -i drerio_sub_fasta.fasta -o new_test
  /gsc/biosw/src/eggnog_mapper/bin/diamond blastp -d /misc/lapras/biodb/EGGNOG/eggnog_proteins.dmnd -q /home/lakatos/ddifraia/eggNOG/drerio_sub_fasta.fasta --threads 4 -o /home/lakatos/ddifraia/eggNOG/new_test.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Funcional annotation of hits...
0 2.384185791015625e-06 0.00 q/s (% mem usage: 24.10, % mem avail: 75.90)`

I already tried different versions of python changing aliases, but still there seems to be no way to fix it. 
In case you want to replicate  this is my test sequence:

`>sp|Q7SZE5|SC23A_DANRE Protein transport protein Sec23A OS=Danio rerio OX=7955 GN=sec23a PE=2 SV=1
MATFQEFIQQNEDRDGVRFSWNVWPSSRLEATRMVVPVASLFTPLKERPDLPPIQYEPVL
CSRATCRAVLNPLCQVDYRAKLWACNFCYQRNQFPPTYAGISEVNQPAELLPQFSTIEYV
VQRGPQMPLNFLYVVDTCMEDDDLQALKESLQMSLSLLPPTALVGLITFGRMVQVHELGC
EGISKSYVFRGTKDLNAKQLQEMLGLTKPAAAQAGRGPQQPQVPPSNRFLQPVQKIDMNL
TDLLGELQRDPWPVTQGKRPLRSLGVALSIAVGLLECTFPNTGARIMAFIGGPATQGPGM
VVGDELKTPIRSWHDIEKDNAKFMKKATKHYEALANRAAANGHIIDIYACALDQTGLLEM
KCCTNYTGGYMVMADSFNTSLFKQTFQRVFTKDVQGCFKMALAGTLEIKTSREIKISGAI
GPCVSLNAKGPCVSENEMGTGGTSQWKICGLDPNTTLGFYFEVVNQHNAPIPQGGRGAIQ
YVTQYQHSSGQRRIRVTTIARNWADAQSQIQSIAASFDQEAAAILMARLAVYKAETEEGP
DVLRWLDRQLIRLCQKFGDYHKEDPNSFRFSETFSLYPQFMFHLRRSPFLQVFNNSPDES
TYYRHQFMRQDLTQSLIMVQPILYAYSFNGPPEPVLLDSSSILPDRILLMDTFFQILIYH
GETVSQWRKAGYQDMPEYENFRHLLQAPVDDAQELLHTRFPMPRYIDTEHGGSQARFLLS
KVNPSQTHNNMYAWGQESGAPILTDDVSLQVFMDHLKKLAVSSAA`

**Comment by Cantalapiedra** [comment]
#299
