### ISSUE TITLE
Error: annotation failed. disk I/O error

### ISSUE THREAD

**Issue by gaoxiangcao** [eggnogdb/eggnog-mapper#340]
HI,I have some trouble in running eggnog with super calculate cluster  ,can you give me some advice? Thanks for your help.
 (eggNOG_mapper) [caogx@mu02 fasta]$ emapper.py -i test.fasta -o test
#  emapper-2.1.5
# emapper.py  -i test.fasta -o test
  /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/bin/diamond blastp -d /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/database/eggnog_proteins.dmnd -q /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/fasta/test.fasta --threads 1 -o /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/fasta/test.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Functional annotation of hits...
0 5.245208740234375e-06 0.00 q/s (% mem usage: 44.70, % mem avail: 55.32)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/eggnogmapper/annotation/annotator_worker.py", line 29, in annotate_hit_line_ondisk
    eggnog_db = get_eggnog_db(usemem = False)
  File "/newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/eggnogmapper/annotation/db_sqlite.py", line 13, in get_eggnog_db
    db = AnnotDB(usemem)
  File "/newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/eggnogmapper/annotation/db_sqlite.py", line 39, in __init__
    curs.execute("PRAGMA synchronous=OFF;")
sqlite3.OperationalError: disk I/O error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/eggnogmapper/annotation/annotator.py", line 250, in _annotate_ondisk
    for result in pool.imap(annotate_hit_line_ondisk,
  File "/newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
sqlite3.OperationalError: disk I/O error
Error: annotation failed. disk I/O error

**Comment by Cantalapiedra** [comment]
Hi @gaoxiangcao ,

I am sorry you having this error.

What is the path to the EGGNOG sqlite db? (it should be a file called eggnog.db.
What is the output of `emapper.py --version --data_dir PATH_TO_EGGNOG_DB`

Is the eggnog.db file stored in an NFS system?
Some users have reported that it is not working in some NFS #212 
You may want to try moving the eggnog.db to a local filesystem (just remember to change the EGGNOG_DATA_DIR env var or use the --data_dir option). If don't want to move also the diamond db, you may need to use also the --dmnd_db option (https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5#diamond-search-options)

Best,
Carlos
