### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory for temporary files.

### ISSUE THREAD

**Issue by KatherineDuchesneau** [eggnogdb/eggnog-mapper#365]
Hello, 

I am trying to run emapper and getting an error with the temporary file creation. 
I am working with Linux on a server and I've installed Eggnog v.2.1.6 using conda. I've also given the following command 500gb of RAM because at first i suspected it might be a memory issue but the error has not changed. 

emapper.py -i file_nrPreds -o file_annotatedPreds --temp_dir . -m hmmer --itype CDS --database 2759 --cpu 1 --dbmem --evalue 0.00001

In response, I get the following error: 

Traceback (most recent call last):
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/bin/emapper.py", line 704, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/eggnogmapper/emapper.py", line 316, in run
    searcher, searcher_name, hits, queries_file = self.search(args, infile, predictor)
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/eggnogmapper/emapper.py", line 165, in search
    raise(e)
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/eggnogmapper/emapper.py", line 162, in search
    pjoin(self._current_dir, self.search_out_file))
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/eggnogmapper/search/hmmer/hmmer.py", line 209, in search
    self.dump_hmm_matches(in_file, hmm_hits_file, dbpath, port, hosts, idmap_file)
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/eggnogmapper/search/hmmer/hmmer.py", line 286, in dump_hmm_matches
    trans_table=self.trans_table):
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/eggnogmapper/search/hmmer/hmmer_search.py", line 135, in hmmcommand
    for name, seq in iter_fasta_seqs(fasta_file, translate=translate, silent=silent, trans_table=trans_table):
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/eggnogmapper/search/hmmer/hmmer_seqio.py", line 15, in iter_fasta_seqs
    from Bio.Alphabet import generic_dna
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x2aaab2e603b0>
Traceback (most recent call last):
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/storage/home/hcoda1/0/user/.conda/envs/Env_Eggnog/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/storage/scratch1/0/user/Working_directory/emappertmp_hmmcmd_l1qxe8jp/tmpbz5f_36d'

Thank you for your help and I am looking forward to hearing back!

**Comment by KatherineDuchesneau** [comment]
solved: python version issues.
