### ISSUE TITLE
sqlite3.OperationalError: no such table: prots

### ISSUE THREAD

**Issue by cylcheyanlin** [eggnogdb/eggnog-mapper#385]
hello,
when I ran the code 
$ emapper.py -m diamond -i pan_genome_reference.fa --itype CDS --translate -o panmaptoeggnog --data_dir /home/database/eggnog5/ --cpu 16

it got the error: 
Traceback (most recent call last):
  File "/home/cheyanlin/miniconda3/envs/eggnog_mapper/lib/python3.7/site-packages/eggnogmapper/annotation/annotator_worker.py", line 61, in annotate_hit_line
    match_nogs = get_member_ogs(best_hit_name, eggnog_db)
  File "/home/cheyanlin/miniconda3/envs/eggnog_mapper/lib/python3.7/site-packages/eggnogmapper/annotation/annotator_worker.py", line 159, in get_member_ogs
    match = eggnog_db.get_member_ogs(name)
  File "/home/cheyanlin/miniconda3/envs/eggnog_mapper/lib/python3.7/site-packages/eggnogmapper/annotation/db_sqlite.py", line 65,in get_member_ogs
    curs.execute('SELECT ogs FROM prots WHERE name == ?;', (name,))
sqlite3.OperationalError: no such table: prots
Error: annotation went wrong for hit ['GPEOPKOH_00001', '1192034.CAP_4404', 1.26e-90, 321.0, 11, 902, 21, 894, 35.6, 98.9, 66.6].no such table: prots

according to the suggestion of the website, ,
I updated sqlite using $conda update sqlite  $conda install sqlite=3.30.1

When I ran the code again, it got the same error.
Functional annotation of hits...
0 8.58306884765625e-06 0.00 q/s (% mem usage: 4.30, % mem avail: 95.69)
Traceback (most recent call last):
  File "/home/cheyanlin/miniconda3/envs/eggnog_mapper/lib/python3.7/site-packages/eggnogmapper/annotation/annotator_worker.py", line 61, in annotate_hit_line
    match_nogs = get_member_ogs(best_hit_name, eggnog_db)
  File "/home/cheyanlin/miniconda3/envs/eggnog_mapper/lib/python3.7/site-packages/eggnogmapper/annotation/annotator_worker.py", line 159, in get_member_ogs
    match = eggnog_db.get_member_ogs(name)
  File "/home/cheyanlin/miniconda3/envs/eggnog_mapper/lib/python3.7/site-packages/eggnogmapper/annotation/db_sqlite.py", line 65,in get_member_ogs
    curs.execute('SELECT ogs FROM prots WHERE name == ?;', (name,))
sqlite3.OperationalError: no such table: prots

when I ran the code $ emapper.py --version, it reported:
There was an error retrieving eggnog-mapper DB data: not a valid file "/home/cheyanlin/miniconda3/envs/eggnog_mapper/lib/python3.7/site-packages/data/eggnog.db"
Maybe you need to run download_eggnog_data.py
emapper-2.1.7 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Diamond version found: diamond version2.0.15 / MMseqs2 version found: 13.45111

when I ran the code : $ sqlite3 /home/DataShare/Database/eggnog5/eggnog.db "select * from version"
2.0

$ sqlite3 /home/DataShare/Database/eggnog5/eggnog.db ".schema"
CREATE TABLE event(
i INTEGER PRIMARY KEY,
level VARCHAR(16),
og VARCHAR(16),
side1 TEXT,
side2 TEXT);
CREATE INDEX event_level_idx ON event (i, level);
CREATE TABLE orthologs(
name VARCHAR(32) PRIMARY KEY,
orthoindex TEXT
);
CREATE TABLE kegg(
name VARCHAR(32) PRIMARY KEY,
ko VARCHAR(256),
cog VARCHAR(256),
disease VARCHAR(256),
ec VARCHAR(256),
brite VARCHAR(256),
rclass VARCHAR(256),
tc VARCHAR(256),
cazy VARCHAR(256),
pathway VARCHAR(256),
module VARCHAR(256),
reaction VARCHAR(256),
go VARCHAR(256),
drug VARCHAR(256),
pubmed VARCHAR(256),
network VARCHAR(256)
);
CREATE TABLE bigg(
name VARCHAR(32) PRIMARY KEY,
reaction VARCHAR(32)
);
CREATE TABLE gene_ontology(
name VARCHAR(32) PRIMARY KEY,
gos TEXT);
CREATE TABLE eggnog(
name VARCHAR(32) PRIMARY KEY,
groups TEXT);
CREATE TABLE og(
og VARCHAR(16),
level VARCHAR(16),
nm INTEGER,
description TEXT,
COG_categories VARCHAR(8),
PRIMARY KEY (og, level)
);
CREATE TABLE seq(
name VARCHAR(32) PRIMARY KEY,
pname VARCHAR(32)
);
CREATE TABLE version(
version VARCHAR(16) PRIMARY KEY);

could you help me? Thanks very much.

**Comment by cylcheyanlin** [comment]
when I download the version of eggnog database again , v5.0.2, it works.
