### ISSUE TITLE
Could not create hmmpgmd servers when using "--pfam_realign denovo"

### ISSUE THREAD

**Issue by biomichal** [eggnogdb/eggnog-mapper#408]
@Cantalapiedra 

Sorry to bother you again. 

First, thanks again for your reply for the last question in GO terms. 

In this issue, I re-run the command again with narrowed parameters to test the GO result. I added the --pfam_realign denovo option, but errors occurred as the following log content. The program cannot create hmmpgmd servers in my local Ubuntu 18.04 system. I searched how to solve it but find nothing. 

So, can you make sure where is the problem in?

Best
Michael

------------------------------------------------------------------------------------------------------------------------------------------------

****Traceback (most recent call last):
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer_server.py", line 73, in create_servers
    sdbpath, shost, sport, master_pid, workers_pids = start_server(dbpath, host, sport, end_port, cpus_per_worker, num_workers, dbtype, silent = silent)
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer_server.py", line 141, in start_server
    raise Exception("Could not start server after trying {ports_tried} ports.")
Exception: Could not start server after trying {ports_tried} ports.
Traceback (most recent call last):
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer_server.py", line 73, in create_servers
    sdbpath, shost, sport, master_pid, workers_pids = start_server(dbpath, host, sport, end_port, cpus_per_worker, num_workers, dbtype, silent = silent)
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer_server.py", line 141, in start_server
    raise Exception("Could not start server after trying {ports_tried} ports.")
Exception: Could not start server after trying {ports_tried} ports.
Traceback (most recent call last):
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer_server.py", line 73, in create_servers
    sdbpath, shost, sport, master_pid, workers_pids = start_server(dbpath, host, sport, end_port, cpus_per_worker, num_workers, dbtype, silent = silent)
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer_server.py", line 141, in start_server
    raise Exception("Could not start server after trying {ports_tried} ports.")
Exception: Could not start server after trying {ports_tried} ports.
Traceback (most recent call last):
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/pfam/pfam.py", line 274, in align_whole_pfam
    s.search_hmm_matches(infile, pfam_file, silent)
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer.py", line 160, in search_hmm_matches
    dbpath, host, port, self.servers = create_servers(self.dbtype, dbpath, host, port, end_port,
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer_server.py", line 93, in create_servers
    raise Exception("Could not create hmmpgmd servers")
Exception: Could not create hmmpgmd servers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/EGG-INFO/scripts/emapper.py", line 701, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/emapper.py", line 347, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/emapper.py", line 284, in run_generator
    for item in generator:
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/deco/decoration.py", line 177, in create_gff
    for hit, annotation in sorted(parse_annotations(annotated_hits),
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/deco/decoration.py", line 312, in parse_annotations
    for hit, annotation in annotated_hits:
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/annotator.py", line 299, in unpack_annotations
    for (hit, annotation), skip in annots:
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/output.py", line 28, in output_orthologs
    for ((hit, annotation), exists) in annots:
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/output.py", line 254, in output_excel
    for (hit, annotation), exists in annots:
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/output.py", line 164, in output_annotations
    for (hit, annotation), exists in annots:
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/pfam/pfam_modes.py", line 31, in run_pfam_mode
    aligned_pfams = pfam_align_denovo(queries_pfams,
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/pfam/pfam_denovo.py", line 24, in pfam_align_denovo
    pfam_aligner.align_whole_pfam(infile, pfam_file, silent = True)
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/annotation/pfam/pfam.py", line 276, in align_whole_pfam
    s.clear()
  File "/data/python3.9/lib/python3.9/site-packages/eggnog_mapper-2.1.8-py3.9.egg/eggnogmapper/search/hmmer/hmmer.py", line 145, in clear
    for dbpath, port, master_pid, workers_pids in self.servers:
TypeError: 'NoneType' object is not iterable****

**Comment by biomichal** [comment]
Solved. I used wrong hmmer version. 
Closed!

**Comment by Cantalapiedra** [comment]
Hi @biomichal,

Sorry for the delay answering. I've been out of office.
Glad that you solved.
I will close the issue.
Please, feel free to re-open or re-issue.

Best,
Carlos
