### ISSUE TITLE
when i run the command  " emapper.py  -i hap1_protein.fasfa --output xx1 --override --cpu 10 --decorate_gff xx.gff3"

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [eggnogdb/eggnog-mapper#414]
when i run the command  " emapper.py  -i hap1_protein.fasfa --output xx1 --override --cpu 10 --decorate_gff xx.gff3"

the xx.gff3 was maked by the evm and update with the funatation. but its error with show

Functional annotation of hits...
0 8.58306884765625e-06 0.00 q/s (% mem usage: 39.20, % mem avail: 60.77)
Decorating gff file xx.gff3...
Traceback (most recent call last):
  File "/public/home/zhaoli/software/eggnog-mapper-master/emapper.py", line 704, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/public/home/zhaoli/software/eggnog-mapper-master/eggnogmapper/emapper.py", line 350, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "/public/home/zhaoli/software/eggnog-mapper-master/eggnogmapper/emapper.py", line 287, in run_generator
    for item in generator:
  File "/public/home/zhaoli/software/eggnog-mapper-master/eggnogmapper/deco/decoration.py", line 90, in decorate_gff
    (g_seqid, g_source, g_type, g_start, g_end,
ValueError: not enough values to unpack (expected 9, got 1)

**Comment by Cantalapiedra** [comment]
Hi @Jiangjiangzhang6 ,

When parsing your gff emapper is expecting a tab delimited file with 9 fields, as in
https://www.ensembl.org/info/website/upload/gff3.html

Is it your gff file like this?

**Comment by Jiangjiangzhang6** [comment]
![image](https://user-images.githubusercontent.com/101324838/193445044-2df62707-9f6e-42b3-bde2-65b67dc3639a.png)

**Comment by Jiangjiangzhang6** [comment]
> Hi @Jiangjiangzhang6 ,
> 
> When parsing your gff emapper is expecting a tab delimited file with 9 fields, as in https://www.ensembl.org/info/website/upload/gff3.html
> 
> Is it your gff file like this?
> 
> `grep -v "^#" xx.gff3 | awk -F $'\t' '{print NF}' | uniq`

its like this ,
![image](https://user-images.githubusercontent.com/101324838/193445060-6609323e-84f9-41fd-835f-771542956258.png)

**Comment by Cantalapiedra** [comment]
Please, try to check that all your rows are the same format:

`grep -v "^#" xx.gff3 | awk -F $'\t' '{print NF}' | uniq`

**Comment by Jiangjiangzhang6** [comment]
its show 0 and 9 
![image](https://user-images.githubusercontent.com/101324838/193445159-e257be94-89ad-4636-bb80-39bf385a5c42.png)

**Comment by Cantalapiedra** [comment]
It should show only 9. Maybe you could try to find the error row:

`grep -v "^#" xx.gff3 | awk -F $'\t' '{if (NF!=9) print NR"\t"$0}'`

**Comment by Jiangjiangzhang6** [comment]
maybe I know error , its would not allow blank line

**Comment by Cantalapiedra** [comment]
I hope it is working now.

Best,
Carlos

**Comment by Jiangjiangzhang6** [comment]
thank you for your reply , now submit it to the cluster,
thank you

**Comment by Cantalapiedra** [comment]
I am closing this issue.
Please, re-open if needed.
