### ISSUE TITLE
Error in run emapper.py

### ISSUE THREAD

**Issue by TianleiQiu** [eggnogdb/eggnog-mapper#420]
Hi,
When I run the emapper.py, some errors came out like belowing,

Traceback (most recent call last):
  File "/public1/home/sc51052/soft/miniconda2/bin/emapper.py", line 4, in <module>
    __import__('pkg_resources').run_script('eggnog-mapper==2.1.9', 'emapper.py')
  File "/public1/home/sc51052/soft/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public1/home/sc51052/soft/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1523, in run_script
    script_code = compile(script_text, script_filename, 'exec')
  File "/public1/home/sc51052/soft/miniconda2/lib/python2.7/site-packages/eggnog_mapper-2.1.9-py2.7.egg/EGG-INFO/scripts/emapper.py", line 94
    help=f'Input FASTA file containing query sequences (proteins by default; see --itype and --translate). '
                                                                                                           ^
SyntaxError: invalid syntax
-------------------------------------------------------------------------------------------------------------------------------------
This is my first time to use eggnog mapper. Please help me, thanks!

**Comment by Cantalapiedra** [comment]
Hi @TianleiQiu ,

Maybe using python 3 (likely >=3.7) will solve your problems.
Python 2.7 is not supported with emapper 2.1.9.

Best,
Carlos

**Comment by TianleiQiu** [comment]
Thanks, I used python 3.9 instead of 2.7, and it works!

**Comment by Cantalapiedra** [comment]
Thank you for reporting back.

Best,
Carlos
