### ISSUE TITLE
ValueError: invalid mode: 'rU' when running emapper.py with the --md5 option

### ISSUE THREAD

**Issue by samuelruizperez** [eggnogdb/eggnog-mapper#432]
Hi!

After installing **eggnog-mapper v2.1.9** through conda (Python 3.11.0) and running `emapper.py` with the `--md5` option I got this error:

```
Creating md5 hashes of input sequences

Parsing fasta file /path/to/proteins.fa...

Traceback (most recent call last):
  File "/home/usr/.conda/envs/env_name/bin/emapper.py", line 704, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/.conda/envs/env_name/lib/python3.11/site-packages/eggnogmapper/emapper.py", line 342, in run
    annotated_hits = self.annotate(args, hits, annotate_hits_table, queries_file, cache_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/.conda/envs/env_name/lib/python3.11/site-packages/eggnogmapper/emapper.py", line 232, in annotate
    annotated_hits = annotator.annotate(annot_in,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/.conda/envs/env_name/lib/python3.11/site-packages/eggnogmapper/annotation/annotator.py", line 108, in annotate
    md5_queries = md5_seqs(queries_file, translate, self.trans_table)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/.conda/envs/env_name/lib/python3.11/site-packages/eggnogmapper/annotation/annotator.py", line 407, in md5_seqs
    for name, seq in iter_fasta_seqs(fasta_file, translate=translate, trans_table=trans_table):
  File "/home/usr/.conda/envs/env_name/lib/python3.11/site-packages/eggnogmapper/search/hmmer/hmmer_seqio.py", line 26, in iter_fasta_seqs
    _source = open(source, "rU")
              ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```
I'm not sure if this is the correct place to post this bug, but I guess the problem is that the `'U'` option is the default behavior of the `open()` function since Python 3.0, and it was deprecated in Python 3.11. I removed the `'U'` from `_source = open(source, "rU")` and it is working fine.

Thanks!

**Comment by samuelruizperez** [comment]
Yes! Works fine with Python 3.9.15.

**Comment by Cantalapiedra** [comment]
Thank you Samuel! And sorry for the headaches

**Comment by Cantalapiedra** [comment]
This should be fixed in version 2.1.10.
Please, re-open if needed.

**Comment by taylorreiter** [comment]
I encountered this error with mode `--translate`, also fixed by downgrading python. I think it might be from this line of code:
https://github.com/eggnogdb/eggnog-mapper/blob/69c8afd4b4dee6647ea939fca9d459903aa10d38/eggnogmapper/utils.py#L233

**Comment by Cantalapiedra** [comment]
Thank you very much!
We will try to fix it ASAP
