### ISSUE TITLE
problem with decorating the gff file

### ISSUE THREAD

**Issue by feudalab** [eggnogdb/eggnog-mapper#455]
Hello,

I am trying to get a decorated gff file,  but I get the following error:
Funcional annotation of hits...
0 3.814697265625e-06 0.00 q/s (% mem usage: 11.20, % mem avail: 88.76)
Decorating gff file  ...
Traceback (most recent call last):
  File "/data/evassvis/software/anaconda3/envs/eggnog_env/bin/emapper.py", line 662, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/data/evassvis/software/anaconda3/envs/eggnog_env/lib/python3.7/site-packages/eggnogmapper/emapper.py", line 317, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "/data/evassvis/software/anaconda3/envs/eggnog_env/lib/python3.7/site-packages/eggnogmapper/emapper.py", line 255, in run_generator
    for item in generator:
  File "/data/evassvis/software/anaconda3/envs/eggnog_env/lib/python3.7/site-packages/eggnogmapper/deco/decoration.py", line 86, in decorate_gff
    with open(gff_file, 'r') as gff_f:
FileNotFoundError: [Errno 2] No such file or directory: '\xa0'

this is the command I am using:

 /data/evassvis/software/anaconda3/envs/eggnog_env/bin/emapper.py --cpu 18 -o a -m diamond --block_size 5 --index_chunks 1 -i Gene_family_255.fa --evalue 0.001 --score 60 --pident 40 --query_cover 20 --subject_cover 20 --itype proteins --tax_scope auto --target_orthologs all --go_evidence non-electronic --pfam_realign none --report_orthologs --decorate_gff   --data_dir /home/r/rf190/eggnog-mapper-2.1.10/data

Do you know where the problem is?

Best,
Roberto

**Comment by Cantalapiedra** [comment]
Hi @feudalab ,

Maybe the problems is because `--decorate_gff` needs an argument, as show here:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.10#output-options

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi @feudalab ,

But in the last post, is it the same error as in the first one? Like:

File "/data/evassvis/software/anaconda3/envs/eggnog_env/lib/python3.7/site-packages/eggnogmapper/deco/decoration.py", line 86, in decorate_gff
with open(gff_file, 'r') as gff_f:
FileNotFoundError: [Errno 2] No such file or directory: '\xa0'

**Comment by feudalab** [comment]
Sorry, Carlos, I have made a mistake and added an invisible character after yer in  the "--decorate_gff yes"
Roberto

**Comment by Cantalapiedra** [comment]
No worries. I hope it is working fine for you now.
Best,
Carlos
