### ISSUE TITLE
the status showed "Done", but no result can be downloaded, using online eggnog

### ISSUE THREAD

**Issue by sqwwww** [eggnogdb/eggnog-mapper#480]
Hi!

I'm using the online eggnog to annotate my protein sequences. I updated my sequence and click the start button, I saw my job was running in the "Server Status" in "http://eggnog-mapper.embl.de/"(the first picture); 

After five minutes, I found my job showed "Status: Done	Submitted: 2023-09-14	Time elapsed: 5:21" on my job manage site. I tried to download the output files(csv, excel,gff and so on), but it  failed with the error "Files wasn't available on site ". and then I found my my job was still queued in the "Server Status" in "http://eggnog-mapper.embl.de/".

Could you please help me to find out what wrong with it?

and also, Is there a way to know how much time will be spent for the job?

Thanks!

**Comment by CoderWenmingxing** [comment]
Hello, I have the following error when using the latest version of emapper.

There was an error retrieving eggnog-mapper DB data: disk I/O error
Maybe you need to run download_eggnog_data.py
emapper-2.1.10 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Diamond version found: diamond version 2.1.6 / MMseqs2 version found: 13.45111

This is after the run is complete

Functional annotation of hits...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/site-packages/eggnogmapper/annotation/annotator_worker.py", line 29, in annotate_hit_line_ondisk
    eggnog_db = get_eggnog_db(usemem = False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/site-packages/eggnogmapper/annotation/db_sqlite.py", line 13, in get_eggnog_db
    db = AnnotDB(usemem)
    ^^^^^^^^^^^^^^^
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/site-packages/eggnogmapper/annotation/db_sqlite.py", line 39, in __init__
    curs.execute("PRAGMA synchronous=OFF;")
sqlite3.OperationalError: disk I/O error
"""
### There was an error retrieving eggnog-mapper DB data: disk I/O error

**Comment by taprs** [comment]
Hi! I have a similar issue, but in my case the `File wasn't available on site` only pops up for the `GFF` output. Example job ID is `MM_isb6ocg8`. I used Google Chrome v119.0.6045.199 to access the website.

**Comment by Cantalapiedra** [comment]
Hi @taprs ,

We may have a bug after updating the GFF files created by the server.
Please, click on "Access your job files here" to download the "out.emapper.decorated.gff" file.

I hope this solves the problem, while we fix it on the job status web page.

Best,
Carlos

**Comment by taprs** [comment]
This does solve my issue, thanks Carlos!
