### ISSUE TITLE
There was an error retrieving eggnog-mapper DB data: disk I/O error

### ISSUE THREAD

**Issue by CoderWenmingxing** [eggnogdb/eggnog-mapper#481]
Hello, I have the following error when using the latest version of emapper.

There was an error retrieving eggnog-mapper DB data: disk I/O error
Maybe you need to run download_eggnog_data.py
emapper-2.1.10 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Diamond version found: diamond version 2.1.6 / MMseqs2 version found: 13.45111

This is after the run is complete

Functional annotation of hits...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/site-packages/eggnogmapper/annotation/annotator_worker.py", line 29, in annotate_hit_line_ondisk
    eggnog_db = get_eggnog_db(usemem = False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/site-packages/eggnogmapper/annotation/db_sqlite.py", line 13, in get_eggnog_db
    db = AnnotDB(usemem)
    ^^^^^^^^^^^^^^^
  File "/Lustre01/tangchuang/miniconda3/envs/eggnog/lib/python3.11/site-packages/eggnogmapper/annotation/db_sqlite.py", line 39, in __init__
    curs.execute("PRAGMA synchronous=OFF;")
sqlite3.OperationalError: disk I/O error
"""
### There was an error retrieving eggnog-mapper DB data: disk I/O error

**Comment by CoderWenmingxing** [comment]
yes> Related with #340?
